#!/usr/bin/env bash
#
# build.sh — compile the icinga-lighthouse firmware for the LilyGo T-Relay (ESP32)
#            using PlatformIO. Produces .build/.pio/build/<board>/firmware.bin
#
# Usage:
#   ./build.sh                 # compile
#   ./build.sh -t erase        # pass extra targets straight to "pio run"
#   BOARD=esp32dev UPLOAD_SPEED=115200 ./build.sh
#
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SKETCH="$HERE/trelaylaatern.ino"
BUILD="$HERE/.build"
BOARD="${BOARD:-esp32dev}"
UPLOAD_SPEED="${UPLOAD_SPEED:-115200}"   # 921600 is unreliable on some USB-serial bridges

command -v pio >/dev/null 2>&1 || {
  echo "ERROR: PlatformIO (pio) not found." >&2
  echo "  macOS:  brew install platformio   (or: pipx install platformio)" >&2
  echo "  Linux:  pipx install platformio   (or: pip install --user platformio)" >&2
  exit 1
}
[ -f "$SKETCH" ] || { echo "ERROR: sketch not found: $SKETCH" >&2; exit 1; }

mkdir -p "$BUILD/src"
cp -f "$SKETCH" "$BUILD/src/main.ino"

cat > "$BUILD/platformio.ini" <<INI
; Auto-generated by build.sh — edit build.sh, not this file.
[env:esp32dev]
platform = espressif32
board = $BOARD
framework = arduino
monitor_speed = 115200
upload_speed = $UPLOAD_SPEED
lib_deps =
  bblanchon/ArduinoJson@^6.21.3
  arduino-libraries/Ethernet@^2.0.2
INI

echo ">> Building firmware for board '$BOARD'..."
pio run -d "$BUILD" "$@"
echo ">> OK -> $BUILD/.pio/build/$BOARD/firmware.bin"
